### ISSUE TITLE
Support "pure" UTC data flow for date/time values

### ISSUE THREAD

**Issue by rwalkerands** [javaee/jpa-spec#156] opened 2017-08-23 06:28 UTC
As per note at https://github.com/javaee/jpa-spec/issues/63#issuecomment-316994047 "Feel free to open new issues for missing parts", adding a new issue specifically for the comments I made at #63.

**Comment by rwalkerands** [comment] 2017-08-23 06:34
Repeating/combining the relevant messages:

Please consider including support for a "pure UTC" data flow at least in the following specific sense:
* Java default time zone can be set to anything (to be specific, _not_ UTC)
* Some of the attributes of an entity class are specified as `LocalDateTime`, where the values are considered to be in UTC
* Schema generation makes database columns of a "TIMESTAMP-like" type (actually, for MySQL I would override and use DATETIME in order to get a wider range of values)
* Values are sent back/forth to the database "as is"
* At no point do the values get converted to/from the default time zone (or any other time zone), so as to avoid the issue with confusion of values during daylight saving changeover

I don't see how to achieve this with JPA as is.

Until yesterday I have been using an `AttributeConverter` like this, based on code that can be found on several blogs:

```
@Converter(autoApply = true)
public class LocalDateTimeConverter implements
    AttributeConverter<LocalDateTime, Timestamp> {

    @Override
    public Timestamp convertToDatabaseColumn(
            final LocalDateTime attribute) {
        if (attribute == null) {
            return null;
        }
        return Timestamp.valueOf(attribute);
    }

    @Override
    public LocalDateTime convertToEntityAttribute(
            final Timestamp dbData) {
        if (dbData == null) {
            return null;
        }
        return dbData.toLocalDateTime();
    }
}
```

I now realise that although this seems to work, it is wrong, because both `Timestamp.valueOf()` and `Timestamp.toLocalDateTime()` interpret the value as though it were in the default time zone, so the code breaks during daylight saving changeover when there's an hour of time that doesn't "exist" in the default time zone.

For example, consider the test value 2016-10-02 02:02:01, which is a perfectly valid time when interpreted as UTC, but which does not exist in my local time zone (Australia/Sydney). If I (with default time zone Australia/Sydney) use the above converter to persist the `LocalDateTime` value `LocalDateTime.of(2016, 10, 2, 2, 1, 0)`, the value is sent to the database, and stored, as '2016-10-02 03:01:00.0', and when it is read back into a `LocalDateTime`, its value is now one hour out! (I've done exactly this test to confirm.)

My converter is now like this:

```
@Converter(autoApply = true)
public class LocalDateTimeConverter implements
    AttributeConverter<LocalDateTime, Timestamp> {

    @Override
    public Timestamp convertToDatabaseColumn(
            final LocalDateTime attribute) {
        if (attribute == null) {
            return null;
        }
        return Timestamp.from(attribute.toInstant(ZoneOffset.UTC));
    }

    @Override
    public LocalDateTime convertToEntityAttribute(
            final Timestamp dbData) {
        if (dbData == null) {
            return null;
        }
        return LocalDateTime.ofInstant(dbData.toInstant(), ZoneOffset.UTC);
    }
}
```

but this doesn't work as is; it requires the recently-added Hibernate-specific configuration (explained at http://in.relation.to/2016/09/12/jdbc-time-zone-configuration-property/) to specify using UTC when sending `Timestamp` values through JDBC:

```
hibernate.jdbc.time_zone=UTC
```

So, although `LocalDateTime` values are "in theory" separate from concerns about time zones, it seems that when it comes to persisting them as Timestamp values, the values must be interpreted as being in some time zone.

So, please consider providing some way of specifying that `LocalDateTime` values are persisted in a "transparent" way (avoiding all internal time zone conversions along the way), or, if that is not possible, specifying the time zone in which `LocalDateTime` values are to be interpreted.

For anyone reading this who wants to use my code, note that for MySQL you'll need to add these parameters to the JDBC URL:

```
&serverTimezone=UTC&useLegacyDatetimeCode=false
```

otherwise you "fall at the last hurdle" (i.e., the JDBC driver ruins everything when it converts Timestamp values to strings).

Other databases _may_ require something similar.

**Comment by rwalkerands** [comment] 2018-01-22 21:59
Please see https://github.com/javaee/jpa-spec/issues/63#issuecomment-299389738, where, in response to a similar comment, I presented the code examples using ZonedDateTime.

The point remains exactly the same.

**Comment by FelixRiemann** [comment] 2018-01-24 18:03
I think there are two things being mixed here.

One is persisting and retrieving instances of `java.sql.Timestamp` by JDBC. This is where the Hibernate property kicks in (and what the new JPA feature should adopt). So if you have a `Timestamp` instance representing `14:00:00` in UTC (leaving out dates for brevity), JDBC sends `14:00:00` to the database (if `hibernate.jdbc.time_zone = UTC` is set), rather than `15:00:00` (assuming your JVM timezone is UTC+1). Something similar should happen on retrieving the value. So there is the "UTC flow".

The other is the conversion of an unsupported type like `java.time.ZonedDateTime` from and to `java.sql.Timestamp`. This is not an automatism of JPA (if it was, that type wouldn't be unsupported). When reading `ZonedDateTime` from a `Timestamp`, it is not up to JPA to guess the time zone - it wasn't persisted in the database. If one only wants to use UTC in `ZonedDateTime` instances anyway (e.g. with your code `return ZonedDateTime.ofInstant(dbData.toInstant(), ZoneOffset.UTC);`), I recommend using `java.time.Instant` instead.

About `LocalDateTime`: This type is supported with JPA 2.2, so no AttributeConverter is necessary there. I consider it somewhat unsuitable that `LocalDateTime` types are going to be mapped to timestamp values, and it's not clear to me how this is going to be done, but this is a separate issue.

**Comment by westonpace** [comment] 2018-03-16 01:18
I agree that `Instant` or `ZonedDateTime` is preferable to `LocalDateTime`.  `LocalDateTime` is fine for storing into the database but not for pulling from the database.  The problem is, in order to do anything with `LocalDateTime`, I have to specify a timezone, which defeats the purpose of the workflow as I understand it.

For example, consider this use case.  I want to pull the next row from the "events" table and print how many seconds are between the current time and the event's "start" column (which is stored as a TIMESTAMP without TZ info, implicitly assumed to be UTC).

If the ORM gives me a `LocalDateTime` instance then I can't compute the number of seconds between that and the current time without populating a timezone so I would have to specify UTC somewhere in my code which defeats the purpose.

On the other hand, if the ORM gives me an Instant instance then I can compute the difference very easily.

This is the entire reason that `LocalDateTime` is currently used for "TIMESTAMP WITHOUT TZ" is that it forces the user to specify the timezone (instead of the ORM guessing the timezone).  If we are doing a "pure UTC" workflow then the user should not have to specify the timezone and the ORM should be the one guessing.

Consider grabbing and storing the current time.  With `Instant` I simply say `Instant.now()` and store that.  The ORM calculates the proper "TIMESTAMP WITHOUT TZ" value for UTC and stores that.

When using `LocalDateTime` the ORM could guess the instance was created using `LocalDateTime.now()` and so is in the local time but if it was created using some other mechanism and thus not in the local time zone then the ORM would store incorrectly.

**Comment by westonpace** [comment] 2018-03-16 01:42
It's possible I misunderstand the goal here too.  My thought would be the goals are:

1) There is a column that is "TIMESTAMP WITHOUT TZ" either because I don't want to store the TZ or I am supporting a legacy database.
2) The ORM should ensure that all values stored in this column are stored in UTC and should take care of returning a TZ-aware object with the TZ set to UTC so that I can't make a mistake later when using it.

**Comment by FelixRiemann** [comment] 2018-05-11 09:12
The "timestamp without tz" (or just "timestamp" for short) is an SQL type which can store an absolute point in time. It does not make sense to say something like "all values stored in this column are stored in UTC" because this type is not timezone aware.

JPA uses JDBC internally to communicate with the database. It uses `java.sql.Timestamp` in conjunction with the SQL `timestamp`, which is perfect, as both represent a point in time.

The problem here is that if you want JPA to store some instance of `java.sql.Timestamp` in the column, a different value will be stored. The same happens when reading from the column. This is somewhat broken. Also see [this blog post](https://vladmihalcea.com/how-to-store-date-time-and-timestamps-in-utc-time-zone-with-jdbc-and-hibernate/)

* One goal here is that the exact same point of time is used in Java and the database. To achieve this goal, no timezone needs to be specified, its just that the JVM tz needs to be ignored. So I'd expect a boolean configuration property would do.
* The second goal is automatic conversion from `java.sql.Timestamp` to the several types in `java.time` by JPA. Only `Instant` is eligible for conversion in both directions without fuzz. But others like `ZonedDateTime` or `LocalDateTime` need a timezone for that. Instead of using the JVM TZ, the TZ could be specified as a configuration property.

**Comment by lukasj** [comment] 2018-08-31 16:58
**Closing this as this issue is migrated to** https://github.com/eclipse-ee4j/jpa-api/issues/156

**Closed by lukasj** 2018-08-31 16:58 UTC
